import type { Series, SeriesId } from "@/lib/chart/types";
import { atr } from "./atr";
import { autocorrelation, compact, logReturns, varianceRatio } from "./autocorr";
import {
  alignedReturns,
  jointDrawdowns,
  middleDaysOf,
  returnCorrelation,
  worstDaysOf,
  type AssetMatrix,
} from "./cross-asset";
import { EDGES, runEdge, type EdgeId } from "./edges";

/**
 * Everything Chapter 8 measures, computed once.
 *
 * Here rather than in `scripts/` for the reason `base-rates.ts` gives: the same code produces
 * the committed artefact and verifies it in CI, and a table generated by one implementation
 * and checked by another only proves the two agree.
 *
 * **Why an artefact at all, rather than computing in the component.** Two reasons, and the
 * second is the binding one. A measurement is not code and only one chapter needs it, so it is
 * fetched like the series. And `lib/levels/kinds/behaviour.ts` is imported eagerly by every
 * level route: a grader reaching into this module would put the variance-ratio estimator in
 * the shared payload of `/level/1-1`. The probe reads a table; it does not carry a statistician.
 *
 * **Nothing in the file is a conclusion.** Issue #26 requires that level 8.2 have the player
 * run the measurement rather than be told the answer, and that requirement survives here: the
 * file holds ratios and z-statistics per horizon, and the crossing point the level grades on
 * is computed from them at play time. The same relationship `base-rates.json` has with
 * Chapter 4 — the numbers are committed, the reading of them is not.
 */

/** The six markets the chapter compares. */
export const SPINE: readonly SeriesId[] = [
  "BTCUSDT-1d",
  "SPY-1d",
  "AAPL-1d",
  "EURUSD-1d",
  "GC-1d",
  "LAKE-1d",
];

/**
 * The window every one of the six covers.
 *
 * Correlation has to live inside it, and so does anything comparing markets to each other:
 * measuring Bitcoin over 2017-2025 against the index over 2005-2023 is an era difference
 * dressed as an asset difference. Variance ratios are reported on full history *as well*,
 * because they are within-asset and more data is simply better there.
 */
export const WINDOW = { from: Date.UTC(2017, 7, 17), to: Date.UTC(2023, 3, 28) };

/** The probe's control grid. Level 8.2's slider must reproduce it exactly. */
export const HORIZONS: readonly number[] = [
  2, 3, 4, 5, 6, 7, 8, 9, 10, 12, 14, 16, 18, 20, 25, 30, 40, 50, 60, 75, 90,
];

export const DEFINITION =
  "A variance ratio compares the variance of a q-bar return against q times the variance " +
  "of a one-bar return. Above 1 the moves reinforce each other; below 1 they cancel; 1.0 " +
  "is a random walk. It is measured on each market's own consecutive bars — including " +
  "Bitcoin's weekends — because a one-bar return means that market's own bar. The z is " +
  "Lo-MacKinlay's heteroskedasticity-robust statistic: under 2 in absolute value, the " +
  "market is not distinguishable from a random walk at that horizon, whatever the ratio " +
  "says. Correlations are the opposite case and use only dates all six markets traded.";

export type AssetFacts = {
  /** Bars inside the shared window. Bitcoin has ~2,081; the equities ~1,434. */
  windowBars: number;
  /** Bars in the market's whole committed history. */
  totalBars: number;
  /** Median 14-bar ATR as a share of close, over full history. */
  atrPct: number;
  /** Lag-1 autocorrelation of log returns, full history. */
  rho1: number;
  /** One entry per horizon, in `HORIZONS` order, over full history. */
  vr: { q: number; vr: number; z: number }[];
};

export type EdgeFacts = {
  id: EdgeId;
  label: string;
  definition: string;
  byAsset: Record<string, { trades: number; totalR: number; perTradeR: number; hitRate: number }>;
  /** `byYear[asset][year]`, restricted to years with at least one trade. */
  byYear: Record<string, Record<string, number>>;
};

export type AssetCharacterFile = {
  definition: string;
  assets: SeriesId[];
  window: { from: string; to: string };
  /** Days all six traded. The cost of honest alignment, reported rather than hidden. */
  alignedDays: number;
  horizons: number[];
  byAsset: Record<string, AssetFacts>;
  correlation: {
    allDays: AssetMatrix;
    /** Days the index sat in its own worst tenth. */
    indexWorstDecile: AssetMatrix;
    /** The middle tenth, for comparison. */
    calmDays: AssetMatrix;
    jointDrawdowns: {
      from: string;
      to: string;
      book: number;
      perAsset: number[];
    }[];
  };
  edges: EdgeFacts[];
};

function medianAtrPct(series: Series<string>): number {
  const values: number[] = [];
  for (let i = 20; i < series.c.length; i += 1) {
    const a = atr(series, i, 14);
    const c = series.c[i];
    if (a > 0 && c !== undefined && c > 0) values.push((a / c) * 100);
  }
  values.sort((x, y) => x - y);
  return values[Math.floor(values.length / 2)] ?? 0;
}

const isoDay = (ms: number) => new Date(ms).toISOString().slice(0, 10);

export function computeAssetCharacter(
  load: (id: SeriesId) => Series<string>,
): AssetCharacterFile {
  const series = SPINE.map((id) => load(id));

  const byAsset: Record<string, AssetFacts> = {};
  SPINE.forEach((id, i) => {
    const s = series[i]!;
    const full = compact(logReturns(s));
    const inWindow = s.t.filter(
      (t) => t >= WINDOW.from && t <= WINDOW.to,
    ).length;

    byAsset[id] = {
      windowBars: inWindow,
      totalBars: s.t.length,
      atrPct: medianAtrPct(s),
      rho1: autocorrelation(full, 1) ?? 0,
      vr: HORIZONS.map((q) => {
        const point = varianceRatio(full, q);
        return { q, vr: point?.vr ?? 1, z: point?.z ?? 0 };
      }),
    };
  });

  const aligned = alignedReturns(series, WINDOW);
  const index = SPINE.indexOf("SPY-1d");

  return {
    definition: DEFINITION,
    assets: [...SPINE],
    window: { from: isoDay(WINDOW.from), to: isoDay(WINDOW.to) },
    alignedDays: aligned.days.length,
    horizons: [...HORIZONS],
    byAsset,
    correlation: {
      allDays: returnCorrelation(SPINE, aligned),
      indexWorstDecile: returnCorrelation(
        SPINE,
        aligned,
        worstDaysOf(aligned, index, 0.1),
      ),
      calmDays: returnCorrelation(
        SPINE,
        aligned,
        middleDaysOf(aligned, index, 0.1),
      ),
      jointDrawdowns: jointDrawdowns(aligned, 5).map((run) => ({
        from: isoDay(run.from * 86_400_000),
        to: isoDay(run.to * 86_400_000),
        book: run.book,
        perAsset: run.perAsset,
      })),
    },
    edges: EDGES.map((edge) => {
      const facts: EdgeFacts = {
        id: edge.id,
        label: edge.label,
        definition: edge.definition,
        byAsset: {},
        byYear: {},
      };
      SPINE.forEach((id, i) => {
        const result = runEdge(series[i]!, edge);
        facts.byAsset[id] = {
          trades: result.trades,
          totalR: result.totalR,
          perTradeR: result.perTradeR,
          hitRate: result.hitRate,
        };
        facts.byYear[id] = result.byYear;
      });
      return facts;
    }),
  };
}
