import { atr } from "./atr";
import { findPatterns, type PatternHit, type PatternKind } from "./patterns";
import type { Series } from "@/lib/chart/types";

/**
 * What a pattern was worth, measured.
 *
 * The computation lives here rather than in `scripts/` so the same code produces the
 * committed artefact and verifies it in CI. A base-rate table generated by one
 * implementation and checked by another only proves the two agree.
 *
 * **The definition is a choice, and it is a crude one.** "Did price close in the
 * signalled direction ten bars later" is easy to state and easy to argue with: it
 * ignores the path, so a pattern whose trade would have been stopped out on bar three
 * still counts as a winner. It is also blind to magnitude, which is why `meanFwdAtr`
 * ships beside `winRate` — a pattern that wins 60% of the time in quarter-ATR
 * increments and loses 40% of the time in whole ones is a losing pattern, and a
 * binary rate hides that completely.
 *
 * `HORIZON` and `DEFINITION` are written into the artefact so the numbers travel with
 * the rule that produced them.
 */

export const HORIZON = 10;

export const DEFINITION =
  "A win is a close in the signalled direction 10 bars after the pattern could first " +
  "be known — its own close for a candle, four bars later for a double top or head " +
  "and shoulders, since the final peak is not a swing high until four bars have " +
  "failed to exceed it. meanFwdAtr is that move in multiples of the 14-bar ATR at " +
  "the same point, so markets of different volatility can be compared. The measure " +
  "ignores the path taken, so a move that would have stopped a real trade out on the " +
  "way still counts as a win — it measures the pattern, not a strategy built on it.";

export type PatternStats = {
  n: number;
  winRate: number;
  meanFwdAtr: number;
  /** Wilson score interval, as [low, high]. */
  ci95: [number, number];
};

/**
 * The Wilson score interval rather than the textbook normal approximation.
 *
 * At the sample sizes that make Chapter 4's point — head and shoulders reaches n=8 on
 * SPY — the normal approximation produces bounds outside [0, 1], which is a visible
 * absurdity in a table the player is asked to read. Wilson stays inside the range and
 * stays sane at small n, which is exactly where the lesson lives.
 */
export function wilsonInterval(wins: number, n: number): [number, number] {
  if (n === 0) return [0, 1];
  const z = 1.959964;
  const p = wins / n;
  const denominator = 1 + (z * z) / n;
  const centre = p + (z * z) / (2 * n);
  const spread = z * Math.sqrt((p * (1 - p)) / n + (z * z) / (4 * n * n));
  return [
    Math.max(0, (centre - spread) / denominator),
    Math.min(1, (centre + spread) / denominator),
  ];
}

/**
 * One pattern's outcome, or null when the horizon runs off the end of the series.
 *
 * Dropped rather than truncated: a pattern measured over four bars because that is
 * all the data left would silently mix horizons.
 */
export function outcomeOf(
  series: Series<string>,
  hit: PatternHit,
): { win: boolean; fwdAtr: number } | null {
  const entry = series.c[hit.confirmedAt];
  const exit = series.c[hit.confirmedAt + HORIZON];
  if (entry === undefined || exit === undefined) return null;

  const volatility = atr(series, hit.confirmedAt);
  if (volatility <= 0) return null;

  const move = exit - entry;
  const signed = hit.direction === "bullish" ? move : -move;
  return { win: signed > 0, fwdAtr: signed / volatility };
}

export function statsFor(
  series: Series<string>,
  kind: PatternKind,
): PatternStats {
  const outcomes = findPatterns(series, kind)
    .map((hit) => outcomeOf(series, hit))
    .filter((o): o is { win: boolean; fwdAtr: number } => o !== null);

  const n = outcomes.length;
  const wins = outcomes.filter((o) => o.win).length;
  const meanFwdAtr =
    n === 0 ? 0 : outcomes.reduce((total, o) => total + o.fwdAtr, 0) / n;

  return {
    n,
    winRate: n === 0 ? 0 : wins / n,
    meanFwdAtr,
    ci95: wilsonInterval(wins, n),
  };
}

/**
 * Pooling across assets, from the per-asset counts.
 *
 * Recomputed from the sums rather than averaged: an unweighted mean of six win rates
 * would let LAKE's 4,600 bars and Bitcoin's 2,778 count equally, and the pooled row
 * exists precisely to show what the *whole* sample says.
 */
export function poolStats(perAsset: PatternStats[]): PatternStats {
  const n = perAsset.reduce((total, s) => total + s.n, 0);
  const wins = perAsset.reduce((total, s) => total + s.winRate * s.n, 0);
  const weighted = perAsset.reduce((total, s) => total + s.meanFwdAtr * s.n, 0);
  const rounded = Math.round(wins);

  return {
    n,
    winRate: n === 0 ? 0 : rounded / n,
    meanFwdAtr: n === 0 ? 0 : weighted / n,
    ci95: wilsonInterval(rounded, n),
  };
}
